import type { SessionStore } from "@/engine/claude/session-store"

type Deps = {
  global: SessionStore
  local: SessionStore
}

/**
 * Keeps repo-local profile execution state out of the global profile store.
 * Local ids carry a reserved prefix generated by localProfileId().
 */
export class FunnelRoutedSessionStore implements SessionStore {
  private readonly global: SessionStore
  private readonly local: SessionStore

  constructor(deps: Deps) {
    this.global = deps.global
    this.local = deps.local
    Object.freeze(this)
  }

  getSessionId(profileId: string): string | null {
    return this.storeFor(profileId).getSessionId(profileId)
  }

  setSessionId(profileId: string, sessionId: string): void {
    this.storeFor(profileId).setSessionId(profileId, sessionId)
  }

  sessionFileExists(cwd: string, sessionId: string, env: Record<string, string>): boolean {
    return this.global.sessionFileExists(cwd, sessionId, env)
  }

  private storeFor(profileId: string): SessionStore {
    return profileId.startsWith("local-") ? this.local : this.global
  }
}
